version: '3.5'

services:
    medicloud:
        build:
            context: '.'
            dockerfile: .docker/Dockerfile
        image: 'laravelapp'
        container_name: medicloud
        volumes:
            - .:/var/www/html
        extra_hosts:
            - "medicloud.local:127.0.0.1"
        hostname: medicloud.local
        domainname: medicloud.local 
        ports:
            - 80:80
        networks:
            backend:
                aliases:
                - medicloud

    mysql-db:
        image: mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql-laravel-db
        ports:
            - "3306:3306"
        volumes:
            - ./run/var:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=medicloud_v3
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
        networks:
            backend:
                aliases:
                - db

networks:
  backend:
    name: backend-network