version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.6
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'medicloud_v3'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql