<div>This is Generated by Cron Jobs : Booking Deactivation </div><br><br>
<?php echo 'Deativated Date : '.$actionDate; ?>
<br>
<?php echo 'Deativated Time : '.$actionTime; ?>
<br>
<?php echo 'Number of Records : '.$totalRecords; ?>
