<div>This is Generated by Cron Jobs : Invoice Generate </div><br><br>
<?php echo 'Invoice Action Date : '.$actionDate; ?>
<br>
<?php echo 'Invoice Action Time : '.$actionTime; ?>
<br>
<?php echo 'Number of Records : '.$totalRecords; ?>
<br />
<?php echo 'Number of Success Invoice : '.$total_success; ?>
<br />
<?php echo 'Number of No Invoice : '.$total_fail; ?>
<br />
@if(isset($total_credits))
	<?php echo 'Total Credits Generate : '.$total_credits; ?>
@endif
